name: Build firmware

on:
  # Triggers the workflow on push or pull request events but only for the "SPACEDOS03A" branch
  push:
    branches: [ "LABDOS01A" ]
  pull_request:
    branches: [ "LABDOS01A" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - type: LABDOS
          - type: LABDOS512
          - type: UAVDOS
            fqbn: clock=8MHz_external
 
    steps:    
        - name: Checkout
          uses: actions/checkout@v2
          continue-on-error: true
          with:
            submodules: recursive
        
        - name: Update git hash
          run: |
            echo "// This file is overwritten by github actions, do not update it manually" > fw/githash.h
            echo "String githash = "\""${{ github.sha }}"\"";" >> fw/githash.h

        - name: Compile all examples
          uses: ArminJo/arduino-test-compile@v3
          with:
            arduino-board-fqbn: MightyCore:avr:1284|${{ matrix.fqbn }}
            platform-url: https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json
            sketch-names-find-start: fw
            
        - name: Store data
          uses: actions/upload-artifact@v3
          with:
            name: fw
            path: fw
            retention-days: 1
            
        - uses: EndBug/add-and-commit@v9
          with:
            message: 'Add build files'
            add: '*.hex'
            fetch: false
