name: Build GoLog app

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: latest
          dest: sw/golog/build
          pkg: sw/golog/
          prefix: sw/golog/src
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
