name: Build firmware

on:
  # Triggers the workflow on push or pull request events but only for the "SPACEDOS03A" branch
  push:
    #branches: [ "LABDOS01A" ]
    paths:
    - 'fw/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: LABDOS
            type: LABDOS
            fqbn: clock=8MHz_external
    
          - name: LABDOS_16Mhz
            type: LABDOS
            fqbn: clock=16MHz_external
            
          - name: LABDOS512
            type: LABDOS512
            fqbn: clock=8MHz_external
            
          - name: LABDOS512_SD
            type: LABDOS512_SD
            fqbn: clock=8MHz_external
            
          - name: UAVDOS
            type: UAVDOS
            fqbn: clock=8MHz_external

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          continue-on-error: true
          with:
            submodules: True

        - name: Update git hash
          run: |
            echo "// This file is overwritten by github actions, do not update it manually" > fw/githash.h
            echo "String githash = "\""${{ github.sha }}"\"";" >> fw/githash.h

        - name: Compile all examples
          uses: ArminJo/arduino-test-compile@v3
          with:
            arduino-board-fqbn: MightyCore:avr:1284:BOD=disabled,LTO=Os,${{ matrix.fqbn }},variant=modelP
            platform-url:  https://mcudude.github.io/MiniCore/package_MCUdude_MiniCore_index.json https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json
            sketch-names-find-start: fw/${{ matrix.type }}
            set-build-path: true
        
        - name: Move to right place
          run: |
            mkdir fw/${{ matrix.type }}/build_${{ matrix.name }}
            mv fw/${{ matrix.type }}/build/* fw/${{ matrix.type }}/build_${{ matrix.name }}/

        - name: Store data
          uses: actions/upload-artifact@v3
          with:
            name: fw_${{ matrix.name }}
            path: fw/${{ matrix.type }}
            retention-days: 1

        - name: Update repository
          run: |
            git pull --no-recurse-submodules

        - uses: EndBug/add-and-commit@v9
          with:
            message: 'Add build files'
            add: '*.hex'
            fetch: false
